theme = "konigi"
baseurl = "http://konigi.com/"
languageCode = "en-us"
title = "Konigi"
MetaDataFormat = "toml"
pluralizeListTitles = false
Paginate = "10"
PageSize = "10"

[taxonomies]
  tag = "tags"
  category = "categories"
  status = "status"
